/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeulabyrinth;

import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author vdruo
 */
public class PartieGraphique extends javax.swing.JFrame {

    Partie partieAssocié;
    int nbJoueur = 0;
    
    
    
    
    /**
     * Creates new form PartieGraphique
     */
    public PartieGraphique() {
        initComponents();
        creerArriereplan();
        ajouterPanneauNomJoueur();
    }

    
    //methode pour creer l'arriere plan, et ajouter les elements graphique par dessus
    public void creerArriereplan() {

        // Charger l'image de fond
        BufferedImage backgroundImage = null;
        try {
            backgroundImage = ImageIO.read(new File("./test/imageFond/imageFond.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Utiliser l'image de fond pour la fenêtre
        setContentPane(new JLabel(new ImageIcon(backgroundImage)));
    }
    
    //methode pour ajouter le panneauJoueurs
    public void ajouterPanneauJoueur(){
        placerElementsPanneauJoueurs();
        setLayout(new BorderLayout());
        panneauJoueurs.setOpaque(false);
        add(panneauJoueurs, BorderLayout.CENTER);
        setVisible(true);
    }
    
    //methode pour placer mes élements sur le pannel PanneauJoueurs
    public void placerElementsPanneauJoueurs(){
        panneauJoueurs.setLayout(new GridBagLayout());
        
        // ajouter le label Combien de joueurs voulez vous ?
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 500, 0);
        panneauJoueurs.add(jLabel1, gbc);
        
        // Créer un groupe de boutons pour en selectionner un a la fois
        ButtonGroup groupeBoutons = new ButtonGroup();
        groupeBoutons.add(bouton2J);
        groupeBoutons.add(bouton3J);
        groupeBoutons.add(bouton4J);
        
        // ajouter les boutons 
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 400, 200);
        panneauJoueurs.add(bouton2J, gbc);
         
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 00, 400, 0);
        panneauJoueurs.add(bouton3J, gbc);
        
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 200, 400, 0);
        panneauJoueurs.add(bouton4J, gbc);
        
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 300, 0);
        panneauJoueurs.add(boutonValider, gbc);
        
        
        
    }
    
    
    //methode pour ajouter le panneauNomJoueurs
    public void ajouterPanneauNomJoueur(){
        placerElementsPanneauNomJoueurs();
        setLayout(new BorderLayout());
        panneauNomJoueurs.setOpaque(false);
        add(panneauNomJoueurs, BorderLayout.CENTER);
        setVisible(true);
    }
    
    //methode pour placer mes élements sur le pannel PanneauJoueurs
    public void placerElementsPanneauNomJoueurs(){
        panneauNomJoueurs.setLayout(new GridBagLayout());
        
        // ajouter le label Combien de joueurs voulez vous ?
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 500, 0);
        panneauNomJoueurs.add(LabelNomJ1, gbc);
        
        
        // ajouter les boutons 
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 400, 0);
        panneauNomJoueurs.add(LabelNomJ2, gbc);
         
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 300, 0);
        panneauNomJoueurs.add(LabelNomJ3, gbc);
        
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 200, 0);
        panneauNomJoueurs.add(LabelNomJ4, gbc);
        
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 0, 0);
        panneauNomJoueurs.add(boutonValider1, gbc);
        
        
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauJoueurs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bouton2J = new javax.swing.JRadioButton();
        bouton3J = new javax.swing.JRadioButton();
        bouton4J = new javax.swing.JRadioButton();
        boutonValider = new javax.swing.JToggleButton();
        panneauNomJoueurs = new javax.swing.JPanel();
        LabelNomJ1 = new javax.swing.JLabel();
        LabelNomJ2 = new javax.swing.JLabel();
        LabelNomJ3 = new javax.swing.JLabel();
        LabelNomJ4 = new javax.swing.JLabel();
        NomJ1 = new javax.swing.JTextField();
        NomJ2 = new javax.swing.JTextField();
        NomJ3 = new javax.swing.JTextField();
        NomJ4 = new javax.swing.JTextField();
        boutonValider1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Combien de joueurs êtes-vous ?");

        bouton2J.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bouton2J.setText("2");

        bouton3J.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bouton3J.setText("3");

        bouton4J.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bouton4J.setText("4");

        boutonValider.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneauJoueursLayout = new javax.swing.GroupLayout(panneauJoueurs);
        panneauJoueurs.setLayout(panneauJoueursLayout);
        panneauJoueursLayout.setHorizontalGroup(
            panneauJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauJoueursLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panneauJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panneauJoueursLayout.createSequentialGroup()
                        .addComponent(bouton2J, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(bouton3J)
                        .addGap(64, 64, 64)
                        .addComponent(bouton4J, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(175, 175, 175))
            .addGroup(panneauJoueursLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(boutonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panneauJoueursLayout.setVerticalGroup(
            panneauJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauJoueursLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panneauJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton2J)
                    .addComponent(bouton3J)
                    .addComponent(bouton4J))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonValider)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(panneauJoueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 260));

        LabelNomJ1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelNomJ1.setText("Nom Joueur 1 :");

        LabelNomJ2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelNomJ2.setText("Nom Joueur 2 :");

        LabelNomJ3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelNomJ3.setText("Nom Joueur 3 :");

        LabelNomJ4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelNomJ4.setText("Nom Joueur 4 :");

        NomJ1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        NomJ2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        NomJ3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        NomJ4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        boutonValider1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boutonValider1.setText("Valider");
        boutonValider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValider1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneauNomJoueursLayout = new javax.swing.GroupLayout(panneauNomJoueurs);
        panneauNomJoueurs.setLayout(panneauNomJoueursLayout);
        panneauNomJoueursLayout.setHorizontalGroup(
            panneauNomJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauNomJoueursLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(panneauNomJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNomJ1)
                    .addComponent(LabelNomJ2)
                    .addComponent(LabelNomJ3)
                    .addComponent(LabelNomJ4))
                .addGap(30, 30, 30)
                .addGroup(panneauNomJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NomJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomJ4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauNomJoueursLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boutonValider1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
        );
        panneauNomJoueursLayout.setVerticalGroup(
            panneauNomJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauNomJoueursLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panneauNomJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panneauNomJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panneauNomJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNomJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panneauNomJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NomJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNomJ4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boutonValider1)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(panneauNomJoueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 670, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // Récupérer la valeur du bouton sélectionné
                if (bouton2J.isSelected()) {
                    nbJoueur = 2;
                    System.out.println(nbJoueur);
                } else if (bouton3J.isSelected()) {
                    nbJoueur = 3;
                    System.out.println(nbJoueur);
                } else if (bouton4J.isSelected()) {
                    nbJoueur = 4;
                    System.out.println(nbJoueur);
                } else {
                    System.out.println("Aucune option sélectionnée");
                }
        //supprimer le panneau
        remove(panneauJoueurs);
         revalidate();
        repaint();
    }//GEN-LAST:event_boutonValiderActionPerformed

    private void boutonValider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValider1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonValider1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartieGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartieGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartieGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartieGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartieGraphique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNomJ1;
    private javax.swing.JLabel LabelNomJ2;
    private javax.swing.JLabel LabelNomJ3;
    private javax.swing.JLabel LabelNomJ4;
    private javax.swing.JTextField NomJ1;
    private javax.swing.JTextField NomJ2;
    private javax.swing.JTextField NomJ3;
    private javax.swing.JTextField NomJ4;
    private javax.swing.JRadioButton bouton2J;
    private javax.swing.JRadioButton bouton3J;
    private javax.swing.JRadioButton bouton4J;
    private javax.swing.JToggleButton boutonValider;
    private javax.swing.JToggleButton boutonValider1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panneauJoueurs;
    private javax.swing.JPanel panneauNomJoueurs;
    // End of variables declaration//GEN-END:variables
}
